name: python-tkinter-skeleton # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: A skeleton for a python3 / tkinter app.
description: |
  Currently unable to run this snap without SEGFAULT.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  skeleton:
    plugin: python
    python-version: python3
    stage-packages: [python3-tk]
    source: .

apps:
  python-tkinter-skeleton:
    environment:
      LC_ALL: C.UTF-8
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu
      LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH
      TCL_LIBRARY: $SNAP/usr/share/tcltk/tcl8.6:$TCL_LIBRARY:$TK_LIBRARY
      TK_LIBRARY: $SNAP/usr/share/tcltk/tk8.6:$TK_LIBRARY:$TCL_LIBRARY
    command: bin/skeleton
    plugs: [home, x11, unity7]
